location:
  name: 15 Broad St, FiDi
  lat: 40.7074
  lng: -74.0113
subway:
  poll_interval_seconds: 30
  stations:
  - name: Wall St
    lines:
    - '4'
    - '5'
    stop_id: 419N
    direction: N
  - name: Wall St
    lines:
    - '2'
    - '3'
    stop_id: 230N
    direction: N
  - name: Broad St
    lines:
    - J
    stop_id: M23S
    direction: W
  - name: Rector St
    lines:
    - '1'
    stop_id: 139N
    direction: N
  - name: Rector St
    lines:
    - R
    - W
    stop_id: R26N
    direction: N
  - name: Fulton St
    lines:
    - A
    - C
    stop_id: A38N
    direction: N
citibike:
  poll_interval_seconds: 60
  stations:
  - name: Broadway & Morris St
    station_id: 7dda8844-60ba-4449-b05c-54c1d14ab5fb
  - name: William St & Pine St
    station_id: 66dbca0f-0aca-11e7-82f6-3863bb44ef7c
  - name: Liberty St & Broadway
    station_id: 66db3583-0aca-11e7-82f6-3863bb44ef7c
  - name: Liberty St & Nassau St
    station_id: e72f0aec-2293-4636-988c-b9d30df092f8
display:
  theme: dark
  orientation: portrait
  refresh_interval_ms: 15000
  staleness_warning_sec: 60
  staleness_critical_sec: 120
