location:
  name: 15 Broad St, FiDi
  lat: 40.7074
  lng: -74.0113
subway:
  poll_interval_seconds: 30
  stations:
  - id: wall_45
    name: Wall St
    lines:
    - '4'
    - '5'
    directions:
    - code: N
      label: Uptown
      stop_id: 419N
    - code: S
      label: Downtown
      stop_id: 419S
  - id: wall_23
    name: Wall St
    lines:
    - '2'
    - '3'
    directions:
    - code: N
      label: Uptown
      stop_id: 230N
    - code: S
      label: Downtown
      stop_id: 230S
  - id: broad_j
    name: Broad St
    lines:
    - J
    directions:
    - code: S
      label: Downtown
      stop_id: M23S
  - id: rector_1
    name: Rector St
    lines:
    - '1'
    directions:
    - code: N
      label: Uptown
      stop_id: 139N
    - code: S
      label: Downtown
      stop_id: 139S
  - id: rector_rw
    name: Rector St
    lines:
    - R
    - W
    directions:
    - code: N
      label: Uptown
      stop_id: R26N
    - code: S
      label: Downtown
      stop_id: R26S
  - id: fulton_ac
    name: Fulton St
    lines:
    - A
    - C
    directions:
    - code: N
      label: Uptown
      stop_id: A38N
    - code: S
      label: Downtown
      stop_id: A38S
citibike:
  poll_interval_seconds: 60
  stations:
  - name: Broadway & Morris St
    station_id: 7dda8844-60ba-4449-b05c-54c1d14ab5fb
  - name: William St & Pine St
    station_id: 66dbca0f-0aca-11e7-82f6-3863bb44ef7c
  - name: Liberty St & Broadway
    station_id: 66db3583-0aca-11e7-82f6-3863bb44ef7c
  - name: Liberty St & Nassau St
    station_id: e72f0aec-2293-4636-988c-b9d30df092f8
display:
  theme: dark
  orientation: portrait
  refresh_interval_ms: 15000
  staleness_warning_sec: 60
  staleness_critical_sec: 120
